#!/bin/sh

### BEGIN INIT INFO
# Provides:          directory
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: directory server
# Description:       directory description
### END INIT INFO

NAME="directory"
DESC="directory description"
LOG=/var/log/node/$NAME.log
PIDFILE=/var/run/$NAME.pid
NODE_ENV="development"
BASE_URL="http://192.168.0.15:3001"
BASE_URL_HTTPS="http://192.168.0.15:3001"
DAEMON=/media/Documents/Projets/2018/directory/bin/www
DAEMON_ARGS=""
SECRET="1234"
EXEC="/usr/bin/nodejs -- $DAEMON" # $DAEMON_ARGS >>$LOG 2>&1
USER=root

[ -x "$DAEMON" ] || exit 0
. /lib/lsb/init-functions

do_start() {
	echo -n "Starting "$NAME" on "$BASE_URL ...
	export NODE_ENV=$NODE_ENV
	export BASE_URL=$BASE_URL
	export BASE_URL_HTTPS=$BASE_URL_HTTPS
	export NAME=$NAME
	export SECRET=$SECRET
	export STARTED=`date +%s`
	start-stop-daemon --start --background --make-pidfile --user "$USER" --pidfile $PIDFILE --exec $EXEC
}

do_stop() {
	echo -n "Stopping "$NAME ...
	start-stop-daemon --stop --remove-pidfile --retry=TERM/30/KILL/5 --pidfile $PIDFILE
	echo 
}

do_status() {
    status_of_proc -p $PIDFILE $DAEMON $NAME
}

case "$1" in
	start)
		do_start
		do_status
    ;;
	stop)
		do_stop
		do_status
    ;;
	restart)
		do_stop
		do_status
		do_start
		do_status
    ;;
	status)
		do_status
    ;;
esac
exit 0
